name: Cart CI

on:
  push:
    paths:
      - 'services/cart/**'

jobs:
  cart-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - working-directory: services/cart
        run: npm install
      - run: echo "✅ Cart service CI passed!"